---
name: Dependency Review

on:
  pull_request:
    types:
      - edited
      - opened
      - reopened
      - synchronize

permissions: {}

jobs:
  dependency-review:
    if: github.event.repository.private == false
    permissions:
      contents: read
    uses: ministryofjustice/analytical-platform-airflow-github-actions/.github/workflows/shared-dependency-review.yml@613a7cc7496ddaed7ae2b12059177d8aeb0760ae # v7.0.0
